language: node_js
node_js:
  - '5'
  - '4'
  - '0.12'
before_install:
  - 'npm install -g npm@latest'
install:
  - 'npm install -g codecov'
script:
  - 'npm run report'
after_success:
  - 'npm run codecov'
